import type { GameDefinition } from '../core/game-controller';

export const GAME_DEFINITIONS: readonly GameDefinition[] = [
  {
    id: 'omok',
    title: '오목',
    shortTitle: '오목',
    eyebrow: 'BRAIN MATCH',
    description: '한 수 앞을 읽고 먼저 다섯 돌을 잇는 정통 보드 대결.',
    players: '2인',
    genre: '두뇌전',
    duration: '3–8분',
    controls: '터치 · 클릭',
    accent: '#ffd447',
    symbol: '五',
    rules: [
      '15×15 교차점에 흑과 백이 번갈아 돌을 놓습니다.',
      '가로, 세로, 양 대각선 중 같은 돌 5개 이상을 먼저 이으면 승리합니다.',
      '기본은 3판 2선승이며 마지막 수만 안전하게 무를 수 있습니다.',
    ],
    load: () => import('../games/omok'),
  },
  {
    id: 'pong',
    title: '네온 탁구',
    shortTitle: '탁구',
    eyebrow: 'REFLEX MATCH',
    description: '각도와 움직임을 실어 받아치는 속도감 있는 네온 랠리.',
    players: '2인',
    genre: '반응 액션',
    duration: '2–4분',
    controls: 'W/S · ↑/↓ · 터치',
    accent: '#45e4e0',
    symbol: '↔',
    landscapePreferred: true,
    rules: [
      'P1은 W/S, P2는 ↑/↓ 또는 각자의 터치 버튼으로 움직입니다.',
      '패들 중심에서 멀리 맞힐수록 공이 더 큰 각도로 반사됩니다.',
      '기본 7점 선취이며 경기 중 공 속도가 서서히 빨라집니다.',
    ],
    load: () => import('../games/pong'),
  },
  {
    id: 'volleyball',
    title: '통통 배구',
    shortTitle: '배구',
    eyebrow: 'BOUNCE MATCH',
    description: '달리고 점프해 공을 상대 코트 바닥에 꽂는 통통 대결.',
    players: '2인',
    genre: '점프 액션',
    duration: '3–5분',
    controls: 'A/D/W · 방향키 · 터치',
    accent: '#ff5d9e',
    symbol: '↑',
    landscapePreferred: true,
    rules: [
      'P1은 A/D/W, P2는 ←/→/↑ 또는 각자의 터치 버튼을 사용합니다.',
      '선수는 네트를 넘을 수 없으며 공이 바닥에 처음 닿으면 상대가 득점합니다.',
      '기본 7점 선취입니다.',
    ],
    load: () => import('../games/volleyball'),
  },
  {
    id: 'pinball-drop',
    title: '핀볼 늦게 떨어지기',
    shortTitle: '핀볼',
    eyebrow: 'TIMING MATCH',
    description: '같은 보드에서 부스터 세 번을 아껴 가장 오래 버티세요.',
    players: '2인',
    genre: '운 + 타이밍',
    duration: '2–4분',
    controls: 'A · L · 터치',
    accent: '#a675ff',
    symbol: '●',
    landscapePreferred: true,
    rules: [
      '두 레인의 핀 배치는 완전히 대칭이고 두 공은 동시에 출발합니다.',
      'P1은 A, P2는 L 또는 각자의 부스터 버튼을 라운드당 세 번 사용합니다.',
      '더 늦게 바닥선을 통과하면 승리하며 0.05초 이하는 무승부입니다.',
    ],
    load: () => import('../games/pinball-drop'),
  },
  {
    id: 'ladder',
    title: '사다리 타기',
    shortTitle: '사다리',
    eyebrow: 'RANDOM PICK',
    description: '2–8명의 이름과 결과를 넣고 하나씩 경로를 공개하세요.',
    players: '2–8인',
    genre: '복불복',
    duration: '2–6분',
    controls: '터치 · 클릭',
    accent: '#58e6a9',
    symbol: 'H',
    rules: [
      '참가자 이름과 결과를 편집한 뒤 사다리를 생성합니다.',
      '각 출발 버튼은 정확히 하나의 서로 다른 결과로 이어집니다.',
      '실행 중에는 참가자 수나 사다리를 바꿀 수 없습니다.',
    ],
    load: () => import('../games/ladder'),
  },
  {
    id: 'reaction-duel',
    title: '반응속도 대결',
    shortTitle: '반응속도',
    eyebrow: 'REACTION DUEL',
    description: '신호가 켜지는 순간 먼저 누르되 성급한 부정 출발을 조심하세요.',
    players: '2인',
    genre: '순간 반응',
    duration: '2–3분',
    controls: 'F · J · 화면 절반',
    accent: '#ff8a4c',
    symbol: '!',
    rules: [
      'P1은 F, P2는 J 또는 각자의 화면 영역을 누릅니다.',
      '신호 전에 누르면 해당 라운드는 부정 출발 패배입니다.',
      '매번 다른 대기 시간으로 진행하며 5판 3선승입니다.',
    ],
    load: () => import('../games/reaction-duel'),
  },
  {
    id: 'tap-battle',
    title: '탭 배틀',
    shortTitle: '탭 배틀',
    eyebrow: 'TAP BATTLE',
    description: '정해진 시간 동안 두 영역을 누구보다 빠르고 정확하게 연타하세요.',
    players: '2인',
    genre: '연타 대결',
    duration: '1분',
    controls: 'F · J · 멀티터치',
    accent: '#6aa8ff',
    symbol: '+',
    rules: [
      'P1은 F, P2는 J 또는 각자의 화면 영역을 연타합니다.',
      '키 자동 반복과 중복 포인터 이벤트는 점수에 포함되지 않습니다.',
      '5초, 10초, 15초 중 시간을 고르고 가장 많이 탭한 사람이 승리합니다.',
    ],
    load: () => import('../games/tap-battle'),
  },
  {
    id: 'roulette',
    title: '벌칙 룰렛',
    shortTitle: '룰렛',
    eyebrow: 'FAIR ROULETTE',
    description: '2–12개의 벌칙을 동일한 확률로 돌리고 결과를 바로 공유하세요.',
    players: '2–12인',
    genre: '랜덤 선택',
    duration: '1–3분',
    controls: '터치 · 클릭',
    accent: '#f4c56a',
    symbol: '◒',
    rules: [
      '2–12개의 항목을 입력하면 모든 칸에 같은 확률이 적용됩니다.',
      '회전을 시작할 때 결과를 먼저 정하고 바늘이 그 칸에 정확히 멈춥니다.',
      '회전 중에는 중복 실행과 항목 편집이 잠깁니다.',
    ],
    load: () => import('../games/roulette'),
  },
];

export function getGameDefinition(id: string): GameDefinition | undefined {
  return GAME_DEFINITIONS.find((game) => game.id === id);
}
